/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:8e2a664d-13f2-43f4-b81d-fe32a6dd74a4",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_yPh1hNDRc",
    "aws_user_pools_web_client_id": "4527g3g8gnh8q66qupfsltmt1g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://yr7f7z6bgjesjkg3b6peoxlsz4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hsw4uarai5a4vapvpeujuszmwe",
    "aws_user_files_s3_bucket": "familychoice815d36abf77749c5b049455311ea427b173143-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
